import { afterEach, describe, expect, test } from "bun:test";
import { mkdir, mkdtemp, readdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";

import { createApp, type CloakHubUpgradeServer, type CloakHubWebSocketData } from "../src/app";
import {
  CapacityUnavailableError,
  UnsupportedManualViewerProfileError,
  type BrowserRuntime,
  type BrowserRuntimeState
} from "../src/browser-runtime";
import type { CloakHubConfig } from "../src/config";
import { ownedProcessEnv } from "../src/owned-process";
import { createProfileService } from "../src/profile-service";
import { openProfileRepository } from "../src/profile-repository";

const cleanupPaths: string[] = [];

afterEach(async () => {
  await Promise.all(cleanupPaths.splice(0).map((path) => rm(path, { force: true, recursive: true })));
});

describe("Browser Profile admin API", () => {
  test("renders Browser Profile management in the UI shell", async () => {
    const { app } = await tempApp({}, undefined, { cdpTokenGenerator: sequenceTokens("profile-token") });
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        display_name: "Work",
        profile_id: "work"
      })
    );

    const response = await app.fetch(new Request("http://cloakhub.test/"));
    const html = await response.text();
    const apiProfile = await (await app.fetch(new Request("http://cloakhub.test/api/profiles/work"))).json();

    expect(response.status).toBe(200);
    expect(apiProfile).toMatchObject({
      platform: "macos",
      screen_height: 768,
      screen_width: 1366
    });
    expect(html).toContain('class="manager-shell"');
    expect(html).toContain('class="profile-sidebar"');
    expect(html).toContain("min-height: 44px;");
    expect(html).toContain("height: calc(100vh - 44px);");
    expect(html).toContain("padding: 6px 8px;");
    expect(html).toContain(".sidebar-head button,");
    expect(html).toContain('id="sidebar-resizer"');
    expect(html).toContain('id="toggle-sidebar"');
    expect(html).toContain('id="show-sidebar"');
    expect(html).toContain('class="viewer-pane"');
    expect(html).toContain("--bg: #efe5d8;");
    expect(html).toContain("--panel: #faf3ea;");
    expect(html).toContain("--panel-strong: #f3e7d8;");
    expect(html).not.toContain("--panel: #fbfdff;");
    expect(html).not.toContain("--bg: #dfeaf2;");
    expect(html).toContain('id="create-profile-modal"');
    expect(html).toContain('id="create-profile-form"');
    expect(html).toContain("create-profile-grid");
    expect(html).toContain('class="create-profile-tabs"');
    expect(html).toContain("Browser information");
    expect(html).toContain("Lower-case letters, numbers, and underscores.");
    expect(html).toContain("Advanced fingerprint and launch settings");
    expect(html).toContain("Stable random seed generated by default.");
    expect(html).toContain("profile-update-form");
    expect(html).toContain("profile-info");
    expect(html).toContain("profile-menu");
    expect(html).toContain('aria-label="View profile work"');
    expect(html).toContain('data-profile-name="Work"');
    expect(html).toContain(">🖥️</button>");
    expect(html).toContain(">ℹ️</button>");
    expect(html).toContain('class="viewer-status"');
    expect(html).toContain("No profile selected");
    expect(html).toContain("popovertarget");
    expect(html).toContain("popover");
    expect(html).toContain("container-type: inline-size");
    expect(html).toContain("@container (max-width: 260px)");
    expect(html).toContain("grid-template-columns: minmax(0, 1fr);");
    expect(html).toContain("justify-content: flex-start;");
    expect(html).not.toContain("gap: 8px;\n        grid-template-columns: minmax(0, 1fr) auto;");
    expect(html).toContain("height: 26px");
    expect(html).toContain(".manual-viewer-button.profile-primary-action");
    expect(html).toContain(".profile-item.selected .manual-viewer-button.profile-primary-action");
    expect(html).not.toContain(".profile-primary-action {\n          display: none;");
    expect(html).not.toContain("VNC/manual");
    expect(html).not.toContain(">Direct<");
    expect(html).toContain('class="profile-edit-modal"');
    expect(html).toContain('class="profile-delete-button"');
    expect(html).toContain('data-action="start"');
    expect(html).toContain('data-action="stop"');
    expect(html).toContain('data-action="restart"');
    expect(html).not.toContain('id="dashboard-filter-form"');
    expect(html).not.toContain("setInterval(refreshDashboard");
    expect(html).toContain("This may disconnect active CDP sessions or viewers.");
    expect(html).toContain('action === "stop"');
    expect(html).not.toContain('action === "restart" &&');
    expect(html).toContain("CDP access is open because no CDP Token exists.");
    expect(html).toContain('class="cdp-token-button" data-action="copy-open-url"');
    expect(html).toContain('class="cdp-token-button" data-action="create"');
    expect(html).toContain('name="proxy"');
    expect(html).toContain('name="fingerprint_seed"');
    expect(html).toContain('name="timezone"');
    expect(html).toContain('name="locale"');
    expect(html).toContain('name="geoip"');
    expect(html).toContain('<select id="create-platform" name="platform">');
    expect(html).toContain('<option value="linux">linux</option>');
    expect(html).toContain('<option value="macos" selected>macos</option>');
    expect(html).toContain('<option value="windows">windows</option>');
    expect(html).toContain('name="platform"');
    expect(html).toContain('name="screen_width"');
    expect(html).toContain('value="1366" aria-label="Screen width"');
    expect(html).toContain('name="screen_height"');
    expect(html).toContain('value="768" aria-label="Screen height"');
    expect(html).toContain('<dd id="create-summary-screen">1366 x 768</dd>');
    expect(html).toContain('name="gpu_vendor"');
    expect(html).toContain('name="gpu_renderer"');
    expect(html).toContain('name="hardware_concurrency"');
    expect(html).toContain('name="user_agent"');
    expect(html).toContain('name="color_scheme"');
    expect(html).toContain('name="humanize"');
    expect(html).toContain('name="human_preset"');
    expect(html).toContain('name="headless"');
    expect(html).toContain('name="clipboard_sync"');
    expect(html).toContain('name="custom_launch_args"');
    expect(html).not.toContain('name="tags_json"');
    expect(html).not.toContain("Tags JSON");
    expect(html).toContain("work");
    expect(html).toContain("Work");

    await app.fetch(new Request("http://cloakhub.test/ui/profiles/work/cdp-token", { method: "POST" }));
    const protectedHtmlResponse = await app.fetch(new Request("http://cloakhub.test/"));
    const protectedHtml = await protectedHtmlResponse.text();

    expect(protectedHtml).toContain("CDP Token is configured.");
    expect(protectedHtml).toContain("Copy token-bearing CDP URL");
    expect(protectedHtml).toContain("Token-bearing CDP URLs can leak access");
    expect(protectedHtml).not.toContain("profile-token");
  });

  test("creates, lists, reads, updates, and deletes stopped Browser Profiles", async () => {
    const { app, dataRoot } = await tempApp();

    const created = await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        display_name: "Work",
        notes: "daily",
        profile_id: "work"
      })
    );
    expect(created.status).toBe(201);
    expect(await created.json()).toMatchObject({ display_name: "Work", profile_id: "work" });
    expect(await readdir(join(dataRoot, "profiles"))).toEqual(["work"]);

    const list = await app.fetch(new Request("http://cloakhub.test/api/profiles"));
    expect(await list.json()).toEqual([
      expect.objectContaining({ display_name: "Work", profile_id: "work" })
    ]);

    const read = await app.fetch(new Request("http://cloakhub.test/api/profiles/work"));
    expect(await read.json()).toMatchObject({ notes: "daily", profile_id: "work" });

    const updated = await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles/work", "PATCH", {
        display_name: "Work 2",
        notes: "updated"
      })
    );
    expect(await updated.json()).toMatchObject({ display_name: "Work 2", notes: "updated" });

    const deleted = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work", { method: "DELETE" })
    );
    expect(deleted.status).toBe(204);
    await expect(readdir(join(dataRoot, "profiles"))).resolves.toEqual([]);
  });

  test("cookie-authenticated UI actions manage Browser Profiles without bearer auth", async () => {
    const { app } = await tempApp({ authToken: "admin-token" });
    const cookie = "cloakhub_auth=admin-token";

    const created = await app.fetch(
      jsonRequest("http://cloakhub.test/ui/profiles", "POST", {
        display_name: "Work",
        profile_id: "work"
      }, cookie)
    );
    expect(created.status).toBe(201);

    const updated = await app.fetch(
      jsonRequest("http://cloakhub.test/ui/profiles/work", "PATCH", {
        display_name: "Work 2"
      }, cookie)
    );
    expect(await updated.json()).toMatchObject({ display_name: "Work 2", profile_id: "work" });

    const deleted = await app.fetch(
      new Request("http://cloakhub.test/ui/profiles/work", {
        headers: { cookie },
        method: "DELETE"
      })
    );
    expect(deleted.status).toBe(204);
  });

  test("rejects invalid, duplicate, and mutable Profile IDs", async () => {
    const { app } = await tempApp();

    const invalid = await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "Work" })
    );
    expect(invalid.status).toBe(400);

    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));
    const duplicate = await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" })
    );
    expect(duplicate.status).toBe(409);

    const mutable = await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles/work", "PATCH", { profile_id: "other" })
    );
    expect(mutable.status).toBe(400);
  });

  test("redacts proxy credentials in API and UI responses while preserving stored metadata", async () => {
    const { app, repository } = await tempApp();

    const created = await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        profile_id: "work",
        proxy: "http://user:secret@proxy.example:8080",
        sleep_policy: { mode: "minutes", minutes: 30 },
        notes: "private notes"
      })
    );
    const body = await created.json();
    const htmlResponse = await app.fetch(new Request("http://cloakhub.test/"));
    const html = await htmlResponse.text();

    expect(body.proxy).toBe("http://user:secret@proxy.example:8080");
    expect(repository.get("work")?.proxy).toBe("http://user:secret@proxy.example:8080");
    expect(html).toContain("private notes");
    expect(html).toContain("http://user:***@proxy.example:8080");
    expect(html).not.toContain("secret");
  });

  test("UI edit preserves stored proxy when the proxy field is left blank", async () => {
    const { app, repository } = await tempApp();
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        profile_id: "work",
        proxy: "http://user:secret@proxy.example:8080"
      })
    );

    const updated = await app.fetch(
      jsonRequest("http://cloakhub.test/ui/profiles/work", "PATCH", {
        _include_empty: "true",
        display_name: "Work 2",
        proxy: ""
      })
    );

    expect(updated.status).toBe(200);
    expect(repository.get("work")?.proxy).toBe("http://user:secret@proxy.example:8080");
  });

  test("shows stopped Instance Status and never-sleep Sleep Policy in API and UI", async () => {
    const { app } = await tempApp();
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        profile_id: "work",
        sleep_policy: { mode: "never" }
      })
    );

    const apiResponse = await app.fetch(new Request("http://cloakhub.test/api/profiles/work"));
    const apiBody = await apiResponse.json();
    const uiResponse = await app.fetch(new Request("http://cloakhub.test/"));
    const html = await uiResponse.text();

    expect(apiBody).toMatchObject({
      instance_status: "stopped",
      sleep_policy: { mode: "never" },
      sleep_policy_status: {
        blocks_sleep: true,
        effective_minutes: null,
        mode: "never"
      }
    });
    expect(html).toContain("stopped");
    expect(html).toContain("Sleep Policy");
    expect(html).toContain("sleep-policy-badge never-sleep");
  });

  test("profile list polling does not count as Instance Activity", async () => {
    const { app, repository } = await tempApp();
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));
    repository.recordActivity("work", "2026-01-01T00:00:00.000Z");
    const before = repository.get("work")?.last_activity_at;

    await app.fetch(new Request("http://cloakhub.test/api/profiles"));
    await app.fetch(new Request("http://cloakhub.test/"));

    expect(repository.get("work")?.last_activity_at).toBe(before);
  });

  test("updates Sleep Policy through the admin API", async () => {
    const { app } = await tempApp();
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));

    const updated = await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles/work", "PATCH", {
        sleep_policy: { mode: "minutes", minutes: 45 }
      })
    );

    expect(await updated.json()).toMatchObject({
      sleep_policy: { mode: "minutes", minutes: 45 },
      sleep_policy_status: {
        blocks_sleep: false,
        effective_minutes: 45,
        mode: "minutes"
      }
    });
  });

  test("starts, stops, and restarts Browser Instances through the admin API", async () => {
    const browserRuntime = fakeBrowserRuntime();
    const { app } = await tempApp({}, browserRuntime);
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        headless: true,
        profile_id: "work"
      })
    );

    const started = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/start", { method: "POST" })
    );
    const stopped = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/stop", { method: "POST" })
    );
    const restarted = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/restart", { method: "POST" })
    );

    expect(await started.json()).toEqual({ profile_id: "work", status: "running" });
    expect(await stopped.json()).toEqual({ profile_id: "work", status: "stopped" });
    expect(await restarted.json()).toEqual({ profile_id: "work", status: "running" });
    expect(browserRuntime.calls).toEqual(["start:work", "stop:work:manual stop", "restart:work"]);
  });

  test("cookie-authenticated UI actions start Browser Instances without bearer auth", async () => {
    const browserRuntime = fakeBrowserRuntime();
    const { app } = await tempApp({ authToken: "admin-token" }, browserRuntime);
    const cookie = "cloakhub_auth=admin-token";

    const response = await app.fetch(
      new Request("http://cloakhub.test/ui/profiles/work/start", {
        headers: { cookie },
        method: "POST"
      })
    );

    expect(response.status).toBe(200);
    expect(browserRuntime.calls).toEqual(["start:work"]);
  });

  test("capacity failures from lifecycle actions are retryable", async () => {
    const browserRuntime = fakeBrowserRuntime({ startError: new CapacityUnavailableError() });
    const { app } = await tempApp({}, browserRuntime);

    const response = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/start", { method: "POST" })
    );

    expect(response.status).toBe(503);
    expect(await response.json()).toEqual({
      error: "Running Instance capacity is full; retry after another Browser Instance stops",
      retryable: true
    });
  });

  test("shows active CDP Session observations in API and UI status", async () => {
    const browserRuntime = fakeBrowserRuntime({ activeCdpSessionCount: 1 });
    const { app } = await tempApp({}, browserRuntime);
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));

    const apiResponse = await app.fetch(new Request("http://cloakhub.test/api/profiles/work"));
    const uiResponse = await app.fetch(new Request("http://cloakhub.test/"));
    const html = await uiResponse.text();

    expect(await apiResponse.json()).toMatchObject({
      cdp_session_count: 1,
      cdp_sessions: [
        {
          duration_ms: 1250,
          remote_address: "203.0.113.10",
          started_at: "2026-01-01T00:00:00.000Z",
          user_agent: "Playwright"
        }
      ]
    });
    expect(html).toContain("1 CDP");
    expect(html).toContain("CDP Sessions");
    expect(html).toContain("Playwright");
    expect(html).toContain("1s");
  });

  test("opens manual viewer with admin auth and triggers headed Transparent Recovery", async () => {
    const browserRuntime = fakeBrowserRuntime();
    const { app } = await tempApp({ authToken: "admin-token" }, browserRuntime);
    const cookie = "cloakhub_auth=admin-token";
    await app.fetch(
      jsonRequest("http://cloakhub.test/ui/profiles", "POST", {
        headless: false,
        profile_id: "work"
      }, cookie)
    );

    const anonymous = await app.fetch(new Request("http://cloakhub.test/ui/profiles/work/viewer"));
    expect(anonymous.status).toBe(401);

    const response = await app.fetch(
      new Request("http://cloakhub.test/ui/profiles/work/viewer", { headers: { cookie } })
    );
    const html = await response.text();

    expect(response.status).toBe(200);
    expect(browserRuntime.calls).toEqual(["viewer:work"]);
    expect(html).toContain('id="manual-viewer"');
    expect(html).toContain('id="paste-button"');
    expect(html).toContain('data-vnc-websocket-url="/ui/profiles/work/vnc"');
    expect(html).toContain('import RFB from "/assets/novnc/core/rfb.js?v=stock-1"');
    expect(html).toContain("/ui/profiles/work/clipboard");
    expect(html).toContain("rfb.clipboardPasteFrom(text)");
    expect(html).toContain("{ wsProtocols: [] }");
    expect(html).toContain('window.prompt("Paste text to send to the browser")');
    expect(html).not.toContain("<header");
    expect(html).not.toContain('<canvas aria-hidden="true">');
    expect(html).not.toContain("#manual-viewer canvas");
    expect(html).toContain("#manual-viewer > div");
    expect(html).toContain("position: fixed;");
    expect(html).toContain("height: 100vh;");
    expect(html).toContain("width: 100vw;");
    expect(html).toContain("border-radius: 999px;");
    expect(html).toContain("status.hidden = true");
  });

  test("serves noVNC browser modules for the manual viewer", async () => {
    const { app } = await tempApp({ authToken: "admin-token" });

    const response = await app.fetch(new Request("http://cloakhub.test/assets/novnc/core/rfb.js"));

    expect(response.status).toBe(200);
    expect(response.headers.get("content-type")).toContain("text/javascript");
    expect(response.headers.get("cache-control")).toBe("no-store");
    expect(await response.text()).toContain("class RFB");
  });

  test("manual viewer capacity failures are retryable", async () => {
    const browserRuntime = fakeBrowserRuntime({ viewerError: new CapacityUnavailableError() });
    const { app } = await tempApp({}, browserRuntime);

    const response = await app.fetch(new Request("http://cloakhub.test/ui/profiles/work/viewer"));
    const html = await response.text();

    expect(response.status).toBe(503);
    expect(html).toContain("Running Instance capacity is full");
    expect(html).toContain("Retryable");
  });

  test("upgrades manual viewer websocket after headed Transparent Recovery", async () => {
    const browserRuntime = fakeBrowserRuntime();
    const server = fakeUpgradeServer();
    const { app } = await tempApp({ authToken: "admin-token" }, browserRuntime);
    const cookie = "cloakhub_auth=admin-token";
    await app.fetch(
      jsonRequest("http://cloakhub.test/ui/profiles", "POST", {
        headless: false,
        profile_id: "work"
      }, cookie)
    );

    const response = await app.fetch(
      new Request("http://cloakhub.test/ui/profiles/work/vnc", {
        headers: { cookie, upgrade: "websocket" }
      }),
      server
    );

    expect(response).toBeUndefined();
    expect(browserRuntime.calls).toEqual(["viewer:work"]);
    expect(server.upgrades).toEqual([{ profileId: "work", targetHost: "127.0.0.1", targetPort: 5900 }]);
  });

  test("manual viewer websocket capacity failures are retryable JSON", async () => {
    const browserRuntime = fakeBrowserRuntime({ viewerError: new CapacityUnavailableError() });
    const server = fakeUpgradeServer();
    const { app } = await tempApp({ authToken: "admin-token" }, browserRuntime);
    const cookie = "cloakhub_auth=admin-token";

    const response = await app.fetch(
      new Request("http://cloakhub.test/ui/profiles/work/vnc", {
        headers: { cookie, upgrade: "websocket" }
      }),
      server
    );

    expect(response?.status).toBe(503);
    expect(await response?.json()).toEqual({
      error: "Running Instance capacity is full; retry after another Browser Instance stops",
      retryable: true
    });
    expect(server.upgrades).toEqual([]);
  });

  test("status responses include active manual viewer count", async () => {
    const browserRuntime = fakeBrowserRuntime({
      activeManualViewerCount: 2,
      lastManualInputAt: "2026-01-01T00:00:05.000Z"
    });
    const { app } = await tempApp({}, browserRuntime);
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));

    const apiResponse = await app.fetch(new Request("http://cloakhub.test/api/profiles/work"));
    const uiResponse = await app.fetch(new Request("http://cloakhub.test/"));
    const html = await uiResponse.text();

    expect(await apiResponse.json()).toMatchObject({
      last_manual_input_at: "2026-01-01T00:00:05.000Z",
      manual_viewer_count: 2
    });
    expect(html).toContain("2 viewer");
    expect(html).toContain("Viewers");
    expect(html).toContain("Last Manual Input");
    expect(html).toContain("2026-01-01T00:00:05.000Z");
  });

  test("dashboard renders compact profile manager, embedded viewer, and approximate Resource Usage", async () => {
    const browserRuntime = fakeBrowserRuntime({
      activeCdpSessionCount: 1,
      activeManualViewerCount: 2,
      lastManualInputAt: "2026-01-01T00:00:05.000Z"
    });
    const { app, dataRoot, repository } = await tempApp({}, browserRuntime);
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        display_name: "Work",
        profile_id: "work",
        proxy: "http://user:secret@proxy.example:8080"
      })
    );
    repository.markRunning("work", "2026-01-01T00:00:00.000Z");
    repository.recordActivity("work", "2026-01-01T00:02:00.000Z");
    repository.markStopped("work", "capacity preemption", "2026-01-01T00:03:00.000Z");
    repository.setCdpToken("work", "profile-token");
    repository.markLaunchFailed("work", "launch failed for profile-token", "2026-01-01T00:04:00.000Z");
    await mkdir(join(dataRoot, "runtime", "work"), { recursive: true });
    await Bun.write(join(dataRoot, "runtime", "work", "browser.pid"), "999999\n");
    const ownedProcess = Bun.spawn(["/bin/sleep", "30"], {
      detached: true,
      env: ownedProcessEnv(dataRoot, "work"),
      stderr: "ignore",
      stdin: "ignore",
      stdout: "ignore"
    });
    ownedProcess.unref();

    try {
      await Bun.write(join(dataRoot, "runtime", "work", "display.pid"), `${ownedProcess.pid}\n`);

      const response = await app.fetch(new Request("http://cloakhub.test/"));
      const html = await response.text();

      expect(response.status).toBe(200);
      expect(html).toContain('id="sidebar-resizer"');
      expect(html).toContain('id="toggle-sidebar"');
      expect(html).toContain('id="show-sidebar"');
      expect(html).toContain('grid-template-columns: minmax(220px, var(--sidebar-width)) 3px minmax(0, 1fr)');
      expect(html).not.toContain('name="q"');
      expect(html).not.toContain('name="sort"');
      expect(html).toContain("Instance Status");
      expect(html).toContain("1 CDP / 2 viewer");
      expect(html).toContain("CDP Sessions");
      expect(html).toContain('data-cdp-session-count="1"');
      expect(html).toContain("Viewers");
      expect(html).toContain('data-manual-viewer-count="2"');
      expect(html).toContain("Last Manual Input");
      expect(html).toContain("2026-01-01T00:00:05.000Z");
      expect(html).toContain("Sleep Blocker: active CDP Session");
      expect(html).toContain("Approx. Resource Usage:");
      expect(html).toContain(" RSS");
      expect(html).toContain("Owned Processes");
      expect(html).toContain("Last Stop Reason");
      expect(html).toContain("launch failure");
      expect(html).toContain("Last Launch Error");
      expect(html).toContain("launch failed for ***");
      expect(html).toContain("Data Directory");
      expect(html).toContain(join(dataRoot, "profiles", "work"));
      expect(html).not.toContain("<dt>CDP Token</dt>");
      expect(html).toContain("manual-viewer-button");
      expect(html).toContain('id="viewer-frame"');
      expect(html).not.toContain('target="_blank"');
      expect(html).not.toContain("window.open");
      expect(html).toContain("await copyCdpUrl(cdpUrl, event.currentTarget)");
      expect(html).toContain("showCopyFeedback(button)");
      expect(html).toContain(".cdp-token-button.copied");
      expect(html).toContain('document.execCommand("copy")');
      expect(html).not.toContain("refreshDashboard");
      expect(html).toContain("http://user:***@proxy.example:8080");
      expect(html).not.toContain("secret");
      expect(html).not.toContain("profile-token");

      const apiProfile = await (await app.fetch(new Request("http://cloakhub.test/api/profiles/work"))).json();
      expect(apiProfile.resource_usage.owned_process_count).toBe(1);
      expect(apiProfile.resource_usage.rss_bytes).toBeGreaterThan(0);
      expect(apiProfile.sleep_status).toBe("Sleep Blocker: active CDP Session");
    } finally {
      killProcessGroup(ownedProcess.pid);
      await ownedProcess.exited.catch(() => undefined);
    }
  });

  test("dashboard ignores obsolete search query params and renders all profiles", async () => {
    const { app } = await tempApp();
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        display_name: "Client Work",
        profile_id: "work"
      })
    );
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        display_name: "Personal",
        profile_id: "personal"
      })
    );
    await app.fetch(
      jsonRequest("http://cloakhub.test/api/profiles", "POST", {
        display_name: "Archive",
        profile_id: "ops"
      })
    );

    const byName = await (await app.fetch(new Request("http://cloakhub.test/?q=client"))).text();
    const ignoredQuery = await (await app.fetch(new Request("http://cloakhub.test/?q=home"))).text();
    const byProfileId = await (await app.fetch(new Request("http://cloakhub.test/?q=ops"))).text();

    expect(byName).toContain("Client Work");
    expect(byName).toContain("Personal");
    expect(ignoredQuery).toContain("Personal");
    expect(ignoredQuery).toContain("Client Work");
    expect(byProfileId).toContain("Archive");
  });

  test("dashboard script avoids idle polling, reloads after actions, and warns only for active Explicit Stop", async () => {
    const { app } = await tempApp({}, undefined, { cdpTokenGenerator: sequenceTokens("profile-token") });
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));
    await app.fetch(new Request("http://cloakhub.test/ui/profiles/work/cdp-token", { method: "POST" }));

    const html = await (await app.fetch(new Request("http://cloakhub.test/"))).text();
    const dashboard = dashboardScriptHarness(html);

    dashboard.run();
    expect(dashboard.intervalMs).toEqual([]);
    expect(dashboard.createSummaryScreenText).toBe("1366 x 768");

    await dashboard.toggleSidebarButton.click();
    expect(dashboard.managerShellClasses).toContain("sidebar-collapsed");
    await dashboard.showSidebarButton.click();
    expect(dashboard.managerShellClasses).not.toContain("sidebar-collapsed");

    dashboard.confirmResults.push(false);
    await dashboard.stopButton.click();
    expect(dashboard.confirmMessages).toEqual(["This may disconnect active CDP sessions or viewers. Continue?"]);
    expect(dashboard.fetches).toEqual([]);

    dashboard.confirmResults.push(true);
    await dashboard.stopButton.click();
    expect(dashboard.fetches.at(-1)).toEqual({
      method: "POST",
      path: "/ui/profiles/work/stop"
    });
    expect(dashboard.reloads).toBe(1);

    await dashboard.restartButton.click();
    expect(dashboard.confirmMessages).toHaveLength(2);
    expect(dashboard.fetches.at(-1)).toEqual({
      method: "POST",
      path: "/ui/profiles/work/restart"
    });
    expect(dashboard.reloads).toBe(2);

    const fetchesBeforeOpenCopy = dashboard.fetches.length;
    await dashboard.copyOpenButton.click();
    expect(dashboard.clipboardWrites).toEqual([
      "http://cloakhub.test/api/profiles/work/cdp/json/version"
    ]);
    expect(dashboard.copyOpenButton.textContent).toBe("Copied");
    expect(dashboard.copyOpenButton.classes).toContain("copied");
    expect(dashboard.fetches).toHaveLength(fetchesBeforeOpenCopy);
    expect(dashboard.reloads).toBe(2);

    await dashboard.copyTokenButton.click();
    expect(dashboard.clipboardWrites).toEqual([
      "http://cloakhub.test/api/profiles/work/cdp/json/version",
      "http://cloakhub.test/api/profiles/work/cdp/json/version?token=profile-token"
    ]);
    expect(dashboard.copyTokenButton.textContent).toBe("Copied");
    expect(dashboard.copyTokenButton.classes).toContain("copied");
    expect(dashboard.confirmMessages).toHaveLength(2);
    expect(dashboard.reloads).toBe(2);

    await dashboard.viewerButton.click();
    expect(dashboard.viewerSources).toEqual(["/ui/profiles/work/viewer"]);
    expect(dashboard.viewerHeadingText).toBe("Work");
    expect(dashboard.viewerProfileIdText).toBe("work");
    expect(dashboard.profileItemClasses).toContain("selected");
    expect(dashboard.openedUrls).toEqual([]);
    expect(dashboard.reloads).toBe(2);

    const fetchCount = dashboard.fetches.length;
    dashboard.postViewerConnected();
    expect(dashboard.manualViewerCountText).toBe("1");
    expect(dashboard.clientStatusText).toBe("1 viewer");
    expect(dashboard.clientStatusHidden).toBe(false);
    expect(dashboard.stopButtonManualViewerCount).toBe("1");
    expect(dashboard.reloads).toBe(2);
    expect(dashboard.fetches).toHaveLength(fetchCount);
  });

  test("dashboard falls back when token-bearing CDP URL clipboard write is blocked", async () => {
    const { app } = await tempApp({}, undefined, { cdpTokenGenerator: sequenceTokens("profile-token") });
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));
    await app.fetch(new Request("http://cloakhub.test/ui/profiles/work/cdp-token", { method: "POST" }));

    const html = await (await app.fetch(new Request("http://cloakhub.test/"))).text();
    const dashboard = dashboardScriptHarness(html, { rejectClipboardWrite: true });

    dashboard.run();
    await dashboard.copyTokenButton.click();

    expect(dashboard.clipboardWrites).toEqual([
      "http://cloakhub.test/api/profiles/work/cdp/json/version?token=profile-token"
    ]);
    expect(dashboard.copyTokenButton.textContent).toBe("Copied");
    expect(dashboard.copyTokenButton.classes).toContain("copied");
    expect(dashboard.reloads).toBe(0);
  });

  test("manual clipboard endpoint writes text through the Browser Runtime", async () => {
    const browserRuntime = fakeBrowserRuntime();
    const { app } = await tempApp({ authToken: "admin-token" }, browserRuntime);
    const cookie = "cloakhub_auth=admin-token";

    const response = await app.fetch(
      jsonRequest("http://cloakhub.test/ui/profiles/work/clipboard", "POST", { text: "pasted" }, cookie)
    );

    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({ ok: true });
    expect(browserRuntime.calls).toEqual(["clipboard:work:pasted"]);
  });

  test("headless profiles show viewer unavailable without changing headless mode", async () => {
    const browserRuntime = fakeBrowserRuntime({ viewerError: new UnsupportedManualViewerProfileError("work") });
    const { app, repository } = await tempApp({}, browserRuntime);
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { headless: true, profile_id: "work" }));

    const response = await app.fetch(new Request("http://cloakhub.test/ui/profiles/work/viewer"));
    const html = await response.text();

    expect(response.status).toBe(400);
    expect(html).toContain("Manual viewer is unavailable for headless Browser Profiles");
    expect(html).toContain("Edit the profile to disable headless mode");
    expect(repository.get("work")?.headless).toBe(true);
  });

  test("manages one plaintext CDP Token through explicit admin actions", async () => {
    const { app, repository } = await tempApp({}, undefined, {
      cdpTokenGenerator: sequenceTokens("first-token", "second-token")
    });
    await app.fetch(jsonRequest("http://cloakhub.test/api/profiles", "POST", { profile_id: "work" }));

    const initialView = await app.fetch(new Request("http://cloakhub.test/api/profiles/work/cdp-token"));
    expect(await initialView.json()).toEqual({
      cdp_token: null,
      cdp_token_configured: false,
      profile_id: "work"
    });

    const created = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/cdp-token", { method: "POST" })
    );
    expect(created.status).toBe(201);
    expect(await created.json()).toEqual({
      cdp_token: "first-token",
      cdp_token_configured: true,
      profile_id: "work"
    });
    expect(repository.get("work")?.cdp_token).toBe("first-token");

    const profile = await app.fetch(new Request("http://cloakhub.test/api/profiles/work"));
    const profileBody = await profile.json();
    expect(profileBody.cdp_token_configured).toBe(true);
    expect(profileBody.cdp_token).toBeUndefined();

    const viewed = await app.fetch(new Request("http://cloakhub.test/api/profiles/work/cdp-token"));
    expect(await viewed.json()).toEqual({
      cdp_token: "first-token",
      cdp_token_configured: true,
      profile_id: "work"
    });

    const regenerated = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/cdp-token/regenerate", { method: "POST" })
    );
    expect(await regenerated.json()).toEqual({
      cdp_token: "second-token",
      cdp_token_configured: true,
      profile_id: "work"
    });
    expect(repository.get("work")?.cdp_token).toBe("second-token");

    const revoked = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/cdp-token", { method: "DELETE" })
    );
    expect(revoked.status).toBe(204);
    expect(repository.get("work")?.cdp_token).toBeNull();
  });

  test("requires admin auth for CDP Token management and keeps CDP Tokens out of admin auth", async () => {
    const { app } = await tempApp(
      { authToken: "admin-token" },
      undefined,
      { cdpTokenGenerator: sequenceTokens("profile-token") }
    );
    const adminCookie = "cloakhub_auth=admin-token";
    await app.fetch(
      jsonRequest("http://cloakhub.test/ui/profiles", "POST", { profile_id: "work" }, adminCookie)
    );

    const anonymousCreate = await app.fetch(
      new Request("http://cloakhub.test/api/profiles/work/cdp-token", { method: "POST" })
    );
    expect(anonymousCreate.status).toBe(401);

    const created = await app.fetch(
      new Request("http://cloakhub.test/ui/profiles/work/cdp-token", {
        headers: { cookie: adminCookie },
        method: "POST"
      })
    );
    expect(created.status).toBe(201);

    const cdpTokenAsAdminAuth = await app.fetch(
      new Request("http://cloakhub.test/api/profiles", {
        headers: { authorization: "Bearer profile-token" }
      })
    );
    expect(cdpTokenAsAdminAuth.status).toBe(401);
  });
});

async function tempApp(
  overrides: Partial<CloakHubConfig> = {},
  browserRuntime?: BrowserRuntime,
  serviceOptions: { cdpTokenGenerator?: () => string } = {}
) {
  const dataRoot = await mkdtemp(join(tmpdir(), "cloakhub-profile-api-"));
  cleanupPaths.push(dataRoot);
  const repository = openProfileRepository(dataRoot);
  repository.migrate();
  const profileService = createProfileService({ dataRoot, repository, ...serviceOptions });
  const config: CloakHubConfig = {
    authToken: undefined,
    browserBin: undefined,
    dataRoot,
    host: "127.0.0.1",
    maxRunningInstances: 10,
    port: 7788,
    ...overrides
  };

  return { app: createApp(config, { browserRuntime, profileService }), dataRoot, repository };
}

function fakeBrowserRuntime(options: {
  activeCdpSessionCount?: number;
  activeManualViewerCount?: number;
  lastManualInputAt?: string | null;
  startError?: Error;
  viewerError?: Error;
} = {}): BrowserRuntime & { calls: string[] } {
  const calls: string[] = [];
  const state = (profileId: string, status: BrowserRuntimeState["status"]): BrowserRuntimeState => ({
    cdp_port: status === "running" ? 5100 : -1,
    profile_id: profileId,
    status
  });

  return {
    calls,
    activeCdpSessionCount: () => options.activeCdpSessionCount ?? 0,
    activeManualViewerCount: () => options.activeManualViewerCount ?? 0,
    cdpSessionObservations: () =>
      options.activeCdpSessionCount
        ? [
            {
              duration_ms: 1250,
              remote_address: "203.0.113.10",
              started_at: "2026-01-01T00:00:00.000Z",
              user_agent: "Playwright"
            }
          ]
        : [],
    lastManualInputAt: () => options.lastManualInputAt ?? null,
    cleanupOwnedProcessesOnStartup: async () => undefined,
    openCdpSession: () => ({
      close: () => undefined,
      recordMessage: () => undefined
    }),
    openManualViewer: async (profileId) => {
      calls.push(`viewer:${profileId}`);
      if (options.viewerError) {
        throw options.viewerError;
      }

      return {
        display: ":100",
        profile_id: profileId,
        vnc_port: 5900,
        vnc_ws_path: `/ui/profiles/${profileId}/vnc`
      };
    },
    openManualViewerSession: () => ({
      close: () => undefined,
      recordInput: () => undefined
    }),
    recordCdpDiscovery: () => undefined,
    restart: async (profileId) => {
      calls.push(`restart:${profileId}`);
      return state(profileId, "running");
    },
    start: async (profileId) => {
      calls.push(`start:${profileId}`);
      if (options.startError) {
        throw options.startError;
      }

      return state(profileId, "running");
    },
    stop: async (profileId, reason = "manual stop") => {
      calls.push(`stop:${profileId}:${reason}`);
      return state(profileId, "stopped");
    },
    spinDownIdleInstances: async () => [],
    writeManualClipboard: async (profileId, text) => {
      calls.push(`clipboard:${profileId}:${text}`);
    }
  };
}

function fakeUpgradeServer(): CloakHubUpgradeServer & { upgrades: CloakHubWebSocketData[] } {
  const upgrades: CloakHubWebSocketData[] = [];

  return {
    upgrades,
    upgrade: (_request, options) => {
      upgrades.push(options.data);
      return true;
    }
  };
}

function jsonRequest(url: string, method: string, body: unknown, cookie?: string): Request {
  return new Request(url, {
    body: JSON.stringify(body),
    headers: {
      "content-type": "application/json",
      ...(cookie ? { cookie } : {})
    },
    method
  });
}

function sequenceTokens(...tokens: string[]): () => string {
  let index = 0;
  return () => tokens[index++] ?? tokens.at(-1) ?? "profile-token";
}

function dashboardScriptHarness(html: string, options: { rejectClipboardWrite?: boolean } = {}) {
  const script = /<script>([\s\S]*)<\/script>/.exec(html)?.[1];
  if (!script) {
    throw new Error("dashboard script not found");
  }

  const createForm = fakeDashboardElement();
  const createDisplayNameInput = fakeDashboardElement();
  const createHeadlessSelect = fakeDashboardElement({}, "", "false");
  const createLocaleInput = fakeDashboardElement();
  const createProfileIdInput = fakeDashboardElement();
  const createProxyInput = fakeDashboardElement();
  const createScreenHeightInput = fakeDashboardElement({}, "", "768");
  const createScreenWidthInput = fakeDashboardElement({}, "", "1366");
  const createSummaryId = fakeDashboardElement();
  const createSummaryMode = fakeDashboardElement();
  const createSummaryName = fakeDashboardElement();
  const createSummaryProxy = fakeDashboardElement();
  const createSummaryRegion = fakeDashboardElement();
  const createSummaryScreen = fakeDashboardElement();
  const createTabButtons = [
    fakeDashboardElement({ profileTab: "basic" }),
    fakeDashboardElement({ profileTab: "browser" }),
    fakeDashboardElement({ profileTab: "fingerprint" }),
    fakeDashboardElement({ profileTab: "advanced" })
  ];
  const createTabPanels = [
    fakeDashboardElement({ profilePanel: "basic" }),
    fakeDashboardElement({ profilePanel: "browser" }),
    fakeDashboardElement({ profilePanel: "fingerprint" }),
    fakeDashboardElement({ profilePanel: "advanced" })
  ];
  createForm.querySelectorAll = (selector: string) => {
    if (selector === ".profile-tab-button") {
      return createTabButtons;
    }

    if (selector === ".profile-tab-panel") {
      return createTabPanels;
    }

    throw new Error(`unexpected form selector ${selector}`);
  };
  const createTimezoneInput = fakeDashboardElement();
  const createProfileModal = fakeDashboardElement();
  const openCreateButton = fakeDashboardElement();
  const closeCreateButton = fakeDashboardElement();
  const cancelCreateButton = fakeDashboardElement();
  const managerShell = fakeDashboardElement();
  const resizer = fakeDashboardElement();
  const showSidebarButton = fakeDashboardElement();
  const toggleSidebarButton = fakeDashboardElement();
  const stopButton = fakeDashboardElement({
    action: "stop",
    cdpSessionCount: "1",
    manualViewerCount: "0",
    profileId: "work"
  });
  const restartButton = fakeDashboardElement({
    action: "restart",
    cdpSessionCount: "1",
    manualViewerCount: "0",
    profileId: "work"
  });
  const copyOpenButton = fakeDashboardElement({ action: "copy-open-url", profileId: "work" });
  copyOpenButton.textContent = "Copy open CDP URL";
  const copyTokenButton = fakeDashboardElement({ action: "copy-url", profileId: "work" });
  copyTokenButton.textContent = "Copy token-bearing CDP URL";
  const profileItem = fakeDashboardElement({ profileId: "work" });
  const clientStatusContainer = fakeDashboardElement();
  const clientStatus = fakeDashboardElement({
    cdpSessionCount: "0",
    manualViewerCount: "0",
    profileId: "work"
  });
  clientStatusContainer.hidden = true;
  clientStatus.parentElement = clientStatusContainer;
  const manualViewerCount = fakeDashboardElement({ profileId: "work" });
  manualViewerCount.textContent = "0";
  const viewerButton = fakeDashboardElement({ profileId: "work", profileName: "Work" });
  const viewerFrame = { src: "" };
  const viewerHeading = fakeDashboardElement();
  const viewerProfileId = fakeDashboardElement();
  const fetches: Array<{ method: string; path: string }> = [];
  const clipboardWrites: string[] = [];
  const confirmMessages: string[] = [];
  const confirmResults: boolean[] = [];
  const intervalMs: number[] = [];
  const openedUrls: string[] = [];
  const viewerSources: string[] = [];
  let selectedCopyText = "";
  let messageHandler:
    | ((event: { data?: { profile_id?: string; type?: string }; origin: string }) => void)
    | undefined;
  let reloads = 0;

  const document = {
    body: {
      appendChild: () => undefined
    },
    createElement: (tagName: string) => {
      if (tagName !== "textarea") {
        throw new Error(`unexpected created element ${tagName}`);
      }

      const element = {
        remove: () => undefined,
        select: () => {
          selectedCopyText = element.value;
        },
        setAttribute: () => undefined,
        style: {},
        value: ""
      };
      return element;
    },
    execCommand: (command: string) => {
      if (command !== "copy") {
        throw new Error(`unexpected command ${command}`);
      }

      clipboardWrites.push(selectedCopyText);
      return true;
    },
    getElementById: (id: string) => {
      if (id === "create-profile-form") {
        return createForm;
      }

      if (id === "create-display-name") {
        return createDisplayNameInput;
      }

      if (id === "create-headless") {
        return createHeadlessSelect;
      }

      if (id === "create-locale") {
        return createLocaleInput;
      }

      if (id === "create-proxy") {
        return createProxyInput;
      }

      if (id === "create-profile-id") {
        return createProfileIdInput;
      }

      if (id === "create-screen-height") {
        return createScreenHeightInput;
      }

      if (id === "create-screen-width") {
        return createScreenWidthInput;
      }

      if (id === "create-summary-id") {
        return createSummaryId;
      }

      if (id === "create-summary-mode") {
        return createSummaryMode;
      }

      if (id === "create-summary-name") {
        return createSummaryName;
      }

      if (id === "create-summary-proxy") {
        return createSummaryProxy;
      }

      if (id === "create-summary-region") {
        return createSummaryRegion;
      }

      if (id === "create-summary-screen") {
        return createSummaryScreen;
      }

      if (id === "create-timezone") {
        return createTimezoneInput;
      }

      if (id === "create-profile-modal") {
        return createProfileModal;
      }

      if (id === "open-create-profile") {
        return openCreateButton;
      }

      if (id === "close-create-profile") {
        return closeCreateButton;
      }

      if (id === "cancel-create-profile") {
        return cancelCreateButton;
      }

      if (id === "sidebar-resizer") {
        return resizer;
      }

      if (id === "show-sidebar") {
        return showSidebarButton;
      }

      if (id === "toggle-sidebar") {
        return toggleSidebarButton;
      }

      if (id === "viewer-frame") {
        return viewerFrame;
      }

      if (id === "viewer-heading") {
        return viewerHeading;
      }

      if (id === "viewer-profile-id") {
        return viewerProfileId;
      }

      throw new Error(`unexpected element id ${id}`);
    },
    querySelector: (selector: string) => {
      if (selector === ".manager-shell") {
        return managerShell;
      }

      throw new Error(`unexpected selector ${selector}`);
    },
    querySelectorAll: (selector: string) => {
      if (
        selector === ".profile-update-form" ||
        selector === ".profile-delete-button" ||
        selector === ".profile-edit-button" ||
        selector === ".profile-edit-close"
      ) {
        return [];
      }

      if (selector === ".profile-form") {
        return [createForm];
      }

      if (selector === ".manual-viewer-button") {
        return [viewerButton];
      }

      if (selector === ".profile-lifecycle-button") {
        return [stopButton, restartButton];
      }

      if (selector === ".cdp-token-button") {
        return [copyOpenButton, copyTokenButton];
      }

      if (selector === ".profile-item") {
        return [profileItem];
      }

      if (selector === "[data-profile-client-status]") {
        return [clientStatus];
      }

      if (selector === "[data-profile-manual-viewer-count]") {
        return [manualViewerCount];
      }

      if (selector === "[data-manual-viewer-count]") {
        return [stopButton, restartButton];
      }

      throw new Error(`unexpected selector ${selector}`);
    }
  };
  const location = {
    origin: "http://cloakhub.test",
    search: "",
    reload: () => {
      reloads += 1;
    }
  };
  const fetch = async (path: string, options: { method?: string } = {}) => {
    fetches.push({ method: options.method ?? "GET", path });
    return {
      json: async () => ({ cdp_token: "profile-token" }),
      ok: true
    };
  };
  const navigator = {
    clipboard: {
      writeText: async (value: string) => {
        if (options.rejectClipboardWrite) {
          throw new Error("clipboard blocked");
        }

        clipboardWrites.push(value);
      }
    }
  };
  const localStorageValues = new Map<string, string>();
  const localStorage = {
    getItem: (key: string) => localStorageValues.get(key) ?? null,
    setItem: (key: string, value: string) => {
      localStorageValues.set(key, value);
    }
  };
  const window: {
    addEventListener: (
      eventName: string,
      handler: (event: { data?: { profile_id?: string; type?: string }; origin: string }) => void
    ) => void;
    clearTimeout: () => void;
    open: (url: string) => object;
    removeEventListener: () => void;
    setTimeout: () => number;
  } = {
    addEventListener: (
      eventName: string,
      handler: (event: { data?: { profile_id?: string; type?: string }; origin: string }) => void
    ) => {
      if (eventName === "message") {
        messageHandler = handler;
      }
    },
    open: (url: string) => {
      openedUrls.push(url);
      return {};
    },
    removeEventListener: () => undefined,
    clearTimeout: () => undefined,
    setTimeout: () => 1
  };
  const confirm = (message: string) => {
    confirmMessages.push(message);
    return confirmResults.shift() ?? true;
  };
  const setInterval = (_callback: () => void, milliseconds: number) => {
    intervalMs.push(milliseconds);
    return 1;
  };

  return {
    get clipboardWrites() {
      return clipboardWrites;
    },
    confirmMessages,
    confirmResults,
    fetches,
    intervalMs,
    openedUrls,
    postViewerConnected: () => {
      messageHandler?.({
        data: { profile_id: "work", type: "cloakhub-viewer-connected" },
        origin: "http://cloakhub.test"
      });
    },
    get reloads() {
      return reloads;
    },
    get createSummaryScreenText() {
      return createSummaryScreen.textContent;
    },
    get clientStatusHidden() {
      return clientStatusContainer.hidden;
    },
    get clientStatusText() {
      return clientStatus.textContent;
    },
    get manualViewerCountText() {
      return manualViewerCount.textContent;
    },
    get profileItemClasses() {
      return profileItem.classes;
    },
    get stopButtonManualViewerCount() {
      return stopButton.dataset.manualViewerCount;
    },
    get viewerHeadingText() {
      return viewerHeading.textContent;
    },
    get viewerProfileIdText() {
      return viewerProfileId.textContent;
    },
    get viewerSources() {
      return viewerSources.length > 0 ? viewerSources : viewerFrame.src ? [viewerFrame.src] : [];
    },
    restartButton,
    showSidebarButton,
    run: () => {
      const scriptFunction = new Function(
        "document",
        "location",
        "fetch",
        "navigator",
        "window",
        "confirm",
        "setInterval",
        "localStorage",
        "FormData",
        script
      );
      scriptFunction(document, location, fetch, navigator, window, confirm, setInterval, localStorage, FormData);
    },
    stopButton,
    get managerShellClasses() {
      return managerShell.classes;
    },
    toggleSidebarButton,
    viewerButton,
    copyOpenButton,
    copyTokenButton
  };
}

function fakeDashboardElement(dataset: Record<string, string> = {}, href = "", value = "") {
  const handlers = new Map<string, (event: { currentTarget: unknown; preventDefault: () => void }) => unknown>();
  const classes = new Set<string>();
  const styleValues = new Map<string, string>();
  const element = {
    classes,
    dataset,
    href,
    hidden: false,
    parentElement: undefined as { hidden: boolean } | undefined,
    style: {
      setProperty: (name: string, value: string) => {
        styleValues.set(name, value);
      }
    },
    classList: {
      add: (className: string) => {
        classes.add(className);
      },
      contains: (className: string) => classes.has(className),
      remove: (className: string) => {
        classes.delete(className);
      },
      toggle: (className: string, force?: boolean) => {
        const shouldAdd = force ?? !classes.has(className);
        if (shouldAdd) {
          classes.add(className);
        } else {
          classes.delete(className);
        }
        return shouldAdd;
      }
    },
    addEventListener: (
      eventName: string,
      handler: (event: { currentTarget: unknown; preventDefault: () => void }) => unknown
    ) => {
      handlers.set(eventName, handler);
    },
    removeAttribute: () => undefined,
    releasePointerCapture: () => undefined,
    setAttribute: () => undefined,
    setPointerCapture: () => undefined,
    textContent: "",
    value,
    querySelectorAll: (_selector: string): unknown[] => [],
    click: async () => {
      await handlers.get("click")?.({
        currentTarget: element,
        preventDefault: () => undefined
      });
    }
  };
  return element;
}

function killProcessGroup(pid: number): void {
  try {
    process.kill(-pid, "SIGKILL");
  } catch {
    try {
      process.kill(pid, "SIGKILL");
    } catch {
      // The test process may have already exited.
    }
  }
}
